bf16: true
cutoff_len: 1024
dataset: flanV2_cot_10000
ddp_timeout: 180000000
do_train: true
eval_steps: 50.0
eval_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 1
learning_rate: 0.0001
logging_steps: 10
lora_target: all
lr_scheduler_type: cosine
max_samples: null
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
num_train_epochs: 3.0
output_dir: saves/llama3-8b-instruct_flanV2_cot_10000_weight-decay0.9/lora/sft
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 4
save_steps: 500.0
stage: sft
template: qwen2
val_size: 0.1
warmup_ratio: 0.1
use_liger_kernel: true
flash_attn: fa2
